# Generated by Django 3.2.8 on 2021-10-26 22:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 22, 25, 34, 164143, tzinfo=utc)),
        ),
    ]
