# Generated by Django 3.2.9 on 2021-12-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_auto_20211210_2312"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="thumbnail",
            field=models.BinaryField(),
        ),
    ]
