# Generated by Django 3.2.8 on 2021-11-16 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('date_received', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
