# Generated by Django 3.2.9 on 2022-03-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0006_alter_blogpost_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="excerpt",
            field=models.CharField(max_length=255),
        ),
    ]
