# Generated by Django 3.2.8 on 2021-11-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
