# Generated by Django 3.2.8 on 2021-11-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_auto_20211117_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='dkbor', max_length=150),
        ),
    ]
