# Generated by Django 4.0.3 on 2022-03-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.URLField(default='https://github.com/denniesbor/denniesbor.github.io/raw/assets/twist2/greg-jeanneau-9sxeKzuCVoE-unsplash.jpg'),
        ),
    ]
