# Generated by Django 4.0.3 on 2022-03-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Cloud', 'Cloud'), ('Space Sciences', 'Space'), ('Artificial Intelligence', 'Ai'), ('Opinion', 'Opinion'), ('Technology', 'Tech')], default='Space Sciences', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.URLField(default='https://github.com/denniesbor/denniesbor.github.io/raw/assets/twist2/greg-jeanneau-9sxeKzuCVoE-unsplash.jpg'),
        ),
    ]
