# Generated by Django 4.0.3 on 2022-03-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_alter_blogpost_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_src',
            field=models.URLField(default='https://github.com/denniesbor/denniesbor.github.io/raw/assets/twist2/greg-jeanneau-9sxeKzuCVoE-unsplash.jpg'),
        ),
    ]
