# Generated by Django 4.0.3 on 2022-03-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_remove_blogpost_thumbnail_blogpost_thumbnail_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='thumbnail_src',
            new_name='thumbnail',
        ),
    ]
