# Generated by Django 4.0.3 on 2022-03-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_alter_blogpost_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='thumbnail',
        ),
    ]
